ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
onlyBuiltDependencies:
  - better-sqlite3
  - '@playwright/browser-chromium'
overrides:
  '@vue/language-core': npm:@dword-design/vue-language-core-fork
