import { expect, test } from '@playwright/test';
import axios from 'axios';
import pretty from 'pretty';

test('init', async () => {
  const { data } = await axios.get('http://localhost:3000/sitemap.xml');

  expect(
    pretty(data).replace(
      /<!-- XML Sitemap generated by @nuxtjs\/sitemap v[\d.]+ at [\d\-T:.Z]+ -->/,
      '<!-- XML Sitemap generated by @nuxtjs/sitemap <version> at <date> -->',
    ),
  ).toMatchSnapshot();
});
