import { property } from '@dword-design/functions';
import tester from '@dword-design/tester';
import testerPluginNuxt from '@dword-design/tester-plugin-nuxt';
import axios from 'axios';
import pretty from 'pretty';

export default tester(
  {
    async init() {
      expect(
        axios.get('http://localhost:3000/sitemap.xml')
          |> await
          |> property('data')
          |> pretty
          |> (content =>
            content.replace(
              /<!-- XML Sitemap generated by @nuxtjs\/sitemap v[\d.]+ at [\d\-T:.Z]+ -->/,
              '<!-- XML Sitemap generated by @nuxtjs/sitemap <version> at <date> -->',
            )),
      ).toMatchSnapshot(this);
    },
  },
  [testerPluginNuxt()],
);
